export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";
export const AUTH_LOGOUT_USER = "LOGOUT_USER";

export const AUTH_RESET_STATE = "AUTH_RESET_STATE";
