export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
export const CHANGE_PRODUCT_INFO = "CHANGE_PRODUCT_INFO";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";

export const TOGGLE_AUTH_MODAL = "TOGGLE_AUTH_MODAL";

export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_CART_LOGOUT = "CLEAR_CART_LOGOUT";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const SHOP_RESET_STATE = "SHOP_RESET_STATE";
